project:
  type: website

website:
  title: "Indice de verdor (NDVI). Destino Naturaleza"
  open-graph: true
  image: "https://dlizcano.github.io/NDVIhist/hist.png"
  twitter-card: 
    creator: "@dlizcano"
    site: "https://github.com/dlizcano/NDVIhist"
  site-url: "https://dlizcano.github.io/NDVIhist"
  repo-url: "https://github.com/dlizcano/NDVIhist"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

    
editor: visual
lightbox: true

