---
project:
  type: website

website:
  title: "NDVI histograms"
  subtitle: "Para Julieth"
  author: "Diego J. Lizcano"
  citation: 
    url: https://dlizcano.github.io/NDVIhist/
  google-scholar: true
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/dlizcano/NDVIhist
        aria-label: GitHub
        
execute: 
  echo: true
  eval: true
  warning: false
  error: false
  output: asis
  
  
format: 
  html: 
    code-fold: true
    code-summary: "codigo R"
    highlight-style: breezedark
    fig-width: 8
    fig-height: 6
citation: true
google-scholar: true
bibliography: grateful-refs.bib    

lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "png",
  dev.args = list(type = "cairo-png"),
  fig.width = 7,
  fig.height = 5,
  fig.align = "center",
  eval = TRUE,
  echo = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  cache.lazy = FALSE) #option to get large datasets
```

## Question

Are the NDVI frequency distributions different between the whole geography and the tourism predios?



## Set up analysis

Load libraries and set some options.

```{r set_up}
#| warning: false
#| message: false

library(sf) # Simple Features for R
library(terra) # Spatial Data Analysis
library(mapview) # Interactive Viewing of Spatial Data in R
library(grateful) # Facilitate Citation of R Packages 
library (ggplot2) # easy graphs in R

library(dplyr) # filter sf

options(scipen=99999)
options(max.print=99999)
options(stringsAsFactors=F)
```


## Load Rasters (.tif)

```{r}
NDVI_full_montes <- rast("C:/Users/usuario/Downloads/Indice_NDVI_GeografiaMontesMaria_2023.tif")
# plot(NDVI_full_montes)

```


## Load predios (.shp)

```{r}
predios <- st_read("C:/CodigoR/Municipios_DN/shp/predios/PrediosDNA.shp")

```

## View the maps

```{r}
slectedpredios <- predios |>  filter(GEOGRAFIA=="MONTES DE MARIA")
a1 <- aggregate(NDVI_full_montes, 10) #agregate to easy view
mapview(a1) + mapview(slectedpredios)


```


## Extract NDVI for predios

```{r}

NDVI_predios <- terra::extract(NDVI_full_montes, predios, xy=TRUE)

```


### Histogram full geography

```{r}
# convert raster to dataframe
full_montes_df <- as.data.frame(NDVI_full_montes, xy = TRUE) # this works with Raster* objects as well

p<-ggplot(full_montes_df, aes(x=NDVI)) + 
  geom_histogram(color="black", fill="white", bins =100)
p


```


### Histogram for predios

```{r}

q<-ggplot(NDVI_predios, aes(x=NDVI)) + 
  geom_histogram(color="black", fill="white", bins =100)
q


```


## Package Citation

```{r }
pkgs <- cite_packages(output = "paragraph", out.dir = ".")
knitr::kable(pkgs)
# pkgs
```


## Información de la sesión en R.

```{r sesion, results='markup'}
sessionInfo()
```





